#!/usr/bin/env python3

import os

# Path to the virtual environment
VENV_DIR = os.path.expanduser("~/.mosamatic/MosamaticDesktop")

# Get the version of Mosamatic
VERSION = os.popen(f"{VENV_DIR}/bin/pip list | grep mosamatic | awk '{{print $2}}'").read().strip()

print(f"Activating virtual environment and starting Mosamatic Desktop {VERSION}...")

# Activate the virtual environment
activate_cmd = f"source {VENV_DIR}/bin/activate"
os.system(activate_cmd)

# Start Mosamatic Desktop
mosamatic_cmd = f"{VENV_DIR}/bin/mosamatic-desktop"
os.system(mosamatic_cmd)

# Deactivate the virtual environment
deactivate_cmd = "deactivate"
os.system(deactivate_cmd)
