#!/bin/bash

# https://chat.openai.com/c/143bf330-901c-46ea-9115-03b450fdd07d
# Also install Python3 if needed

VENV_DIR="$HOME/.mosamatic/MosamaticDesktop"

echo "Activating virtual environment and starting Mosamatic AI service..."
source $VENV_DIR/bin/activate
$HOME/.mosamatic/MosamaticDesktop/bin/mosamatic-ai-service
deactivate