@echo off

@REM SET "SCRIPTDIR=%~dp0"
@REM SET "SCRIPTDIR=%SCRIPTDIR:~0,-1%"
@REM SET "DATABASE=%SCRIPTDIR%\db.sqlite3"
@REM SET "DATABASEECHO=0"
@REM "%SCRIPT_DIR%\main.exe"

SET DATABASE=db.sqlite3
SET DATABASEECHO=0

call main.exe