@echo off

SET "SCRIPTDIR=%~dp0"
SET "SCRIPTDIR=%SCRIPTDIR:~0,-1%"
SET /p "GITCOMMITID=<%SCRIPTDIR%\gitcommitid.txt"
SET "LOGFILEPATH=${ROOTDIR}/MosamaticDesktop.log"
SET "SETTINGSPATH=%SCRIPTDIR%\settings.ini"
SET "DATABASE=%SCRIPTDIR%\db.sqlite3"
SET "DATABASEECHO=0"

"%SCRIPT_DIR%\MyAppExecutable.exe"